[project]
name = "island-dispatch"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "ablog>=0.11.12",
    "myst-parser>=4.0.1",
    "napari-sphinx-theme>=0.7.0",
    "sphinx>=8.2.3",
    "sphinx-autobuild>=2025.8.25",
]
