version: 2.1

jobs:
  build-blog:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout:
          path: blog
      - run:
          name: Build blog
          command: |
            cd blog
            uv run make html
      - store_artifacts:
          path: blog/build
      - persist_to_workspace:
          root: .
          paths:
            - blog/build
workflows:
  build-blog:
    jobs:
      - build-blog
