name: CircleCI artifact redirector

on: [status]
jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    if: "github.event.context == 'ci/circleci: build-blog'"
    permissions:
      statuses: write
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@839631420e45a08af893032e5a5e8843bf47e8ff # v1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.CIRCLECI_TOKEN }}
          artifact-path: 0/blog/build/index.html
          circleci-jobs: build-blog
          job-title: Blog preview
